### ISSUE TITLE
Form Cleared Without Warning if JavaScript Disabled

### ISSUE THREAD

**Issue by artiemog** [classabbyamp/qsl-generator#1]
If JavaScript is disabled in the browser, the form will appear to load correctly, but clicking the **Generate** button will simply cause the page to refresh to a cleared-out form.

More user-friendly behaviour in this scenario might be something like displaying a "JavaScript is required" warning message, making the button non-functional if JavaScript is disabled, etc.

My test conditions:
JavaScript disabled using the NoScript extension v. 11.0.23
Firefox 74.0 x64
Ubuntu 18.04.4 x64

**Comment by classabbyamp** [comment]
should be an [easy fix](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript)
