### ISSUE TITLE
Add option to show Grid Square

### ISSUE THREAD

**Issue by sneader** [classabbyamp/qsl-generator#10]
Grid Square is an important field to have on any QSL card, especially for VHF and UHF QSOs.  Please consider adding Grid Square.  TU!

**Comment by classabbyamp** [comment]
it's supposed to go in the QTH field

![image](https://github.com/user-attachments/assets/d15977a0-57f8-4c08-be94-1eb1d97f4fa1)

**Comment by sneader** [comment]
Whoops, missed the helper text in the field -- thanks!
